### ISSUE TITLE
Web (CMS)

### ISSUE THREAD

**Issue by Icety** [AreaFiftyLAN/lancie-admin#7]
You need to be able to edit most of the texts and event info of the website itself.
Think about:

- [ ] Sections: all the texts and titles on the frontpage
- [ ] Sponsors:
- [ ] Events
- [ ] Global data: Google maps, banner text, title text
- [ ] Slideshow: Change the images
- [ ] Committee
- [ ] Legal info
- [ ] Terms & Condition
- [ ] Q&A
- [ ] Planning
